
package org.nameapi.client.services.validator.placeholdernamedetector.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;
import org.nameapi.client.commonwsdl.person.SoapSimpleNaturalPerson;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapPlaceholderNameDetector", targetNamespace = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapPlaceholderNameDetector {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "price", targetNamespace = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.placeholdernamedetector.wsdl.Price")
    @ResponseWrapper(localName = "priceResponse", targetNamespace = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.placeholdernamedetector.wsdl.PriceResponse")
    @Action(input = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/SoapPlaceholderNameDetector/priceRequest", output = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/SoapPlaceholderNameDetector/priceResponse")
    public int price();

    /**
     * 
     * @param person
     * @param context
     * @return
     *     returns org.nameapi.client.services.validator.placeholdernamedetector.wsdl.SoapPlaceholderNameResult
     * @throws org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException
     * @throws AccessDeniedWebServiceException
     * @throws InvalidInputWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkPerson", targetNamespace = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.placeholdernamedetector.wsdl.CheckPerson")
    @ResponseWrapper(localName = "checkPersonResponse", targetNamespace = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.placeholdernamedetector.wsdl.CheckPersonResponse")
    @Action(input = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/SoapPlaceholderNameDetector/checkPersonRequest", output = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/SoapPlaceholderNameDetector/checkPersonResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/SoapPlaceholderNameDetector/checkPerson/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/SoapPlaceholderNameDetector/checkPerson/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/SoapPlaceholderNameDetector/checkPerson/Fault/InternalServerErrorWebServiceException")
    })
    public SoapPlaceholderNameResult checkPerson(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "person", targetNamespace = "")
        SoapSimpleNaturalPerson person)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
