
package org.nameapi.client.services.validator.placeholdernamedetector.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapPlaceholderNameDetectorService", targetNamespace = "http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/validator/placeholdernamedetector?wsdl")
public class SoapPlaceholderNameDetectorService
    extends Service
{

    private final static URL SOAPPLACEHOLDERNAMEDETECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPPLACEHOLDERNAMEDETECTORSERVICE_EXCEPTION;
    private final static QName SOAPPLACEHOLDERNAMEDETECTORSERVICE_QNAME = new QName("http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/", "SoapPlaceholderNameDetectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/validator/placeholdernamedetector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPPLACEHOLDERNAMEDETECTORSERVICE_WSDL_LOCATION = url;
        SOAPPLACEHOLDERNAMEDETECTORSERVICE_EXCEPTION = e;
    }

    public SoapPlaceholderNameDetectorService() {
        super(__getWsdlLocation(), SOAPPLACEHOLDERNAMEDETECTORSERVICE_QNAME);
    }

    public SoapPlaceholderNameDetectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPPLACEHOLDERNAMEDETECTORSERVICE_QNAME, features);
    }

    public SoapPlaceholderNameDetectorService(URL wsdlLocation) {
        super(wsdlLocation, SOAPPLACEHOLDERNAMEDETECTORSERVICE_QNAME);
    }

    public SoapPlaceholderNameDetectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPPLACEHOLDERNAMEDETECTORSERVICE_QNAME, features);
    }

    public SoapPlaceholderNameDetectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapPlaceholderNameDetectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapPlaceholderNameDetector
     */
    @WebEndpoint(name = "SoapPlaceholderNameDetectorPort")
    public SoapPlaceholderNameDetector getSoapPlaceholderNameDetectorPort() {
        return super.getPort(new QName("http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/", "SoapPlaceholderNameDetectorPort"), SoapPlaceholderNameDetector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapPlaceholderNameDetector
     */
    @WebEndpoint(name = "SoapPlaceholderNameDetectorPort")
    public SoapPlaceholderNameDetector getSoapPlaceholderNameDetectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://placeholdernamedetector.validator.services.v4_0.soap.server.nameapi.org/", "SoapPlaceholderNameDetectorPort"), SoapPlaceholderNameDetector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPPLACEHOLDERNAMEDETECTORSERVICE_EXCEPTION!= null) {
            throw SOAPPLACEHOLDERNAMEDETECTORSERVICE_EXCEPTION;
        }
        return SOAPPLACEHOLDERNAMEDETECTORSERVICE_WSDL_LOCATION;
    }

}
