
package org.nameapi.client.services.nameparser.fieldnameparser.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapFieldNameParserService", targetNamespace = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org/soap/v4.0/nameparser/fieldnameparser?wsdl")
public class SoapFieldNameParserService
    extends Service
{

    private final static URL SOAPFIELDNAMEPARSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPFIELDNAMEPARSERSERVICE_EXCEPTION;
    private final static QName SOAPFIELDNAMEPARSERSERVICE_QNAME = new QName("http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/", "SoapFieldNameParserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org/soap/v4.0/nameparser/fieldnameparser?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPFIELDNAMEPARSERSERVICE_WSDL_LOCATION = url;
        SOAPFIELDNAMEPARSERSERVICE_EXCEPTION = e;
    }

    public SoapFieldNameParserService() {
        super(__getWsdlLocation(), SOAPFIELDNAMEPARSERSERVICE_QNAME);
    }

    public SoapFieldNameParserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPFIELDNAMEPARSERSERVICE_QNAME, features);
    }

    public SoapFieldNameParserService(URL wsdlLocation) {
        super(wsdlLocation, SOAPFIELDNAMEPARSERSERVICE_QNAME);
    }

    public SoapFieldNameParserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPFIELDNAMEPARSERSERVICE_QNAME, features);
    }

    public SoapFieldNameParserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapFieldNameParserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapFieldNameParser
     */
    @WebEndpoint(name = "SoapFieldNameParserPort")
    public SoapFieldNameParser getSoapFieldNameParserPort() {
        return super.getPort(new QName("http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/", "SoapFieldNameParserPort"), SoapFieldNameParser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapFieldNameParser
     */
    @WebEndpoint(name = "SoapFieldNameParserPort")
    public SoapFieldNameParser getSoapFieldNameParserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/", "SoapFieldNameParserPort"), SoapFieldNameParser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPFIELDNAMEPARSERSERVICE_EXCEPTION!= null) {
            throw SOAPFIELDNAMEPARSERSERVICE_EXCEPTION;
        }
        return SOAPFIELDNAMEPARSERSERVICE_WSDL_LOCATION;
    }

}
