
package org.nameapi.client.services.nameparser.fieldnameparser.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;
import org.nameapi.client.commonwsdl.person.SoapNameField;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapFieldNameParser", targetNamespace = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapFieldNameParser {


    /**
     * 
     * @param nameField
     * @param context
     * @return
     *     returns org.nameapi.client.services.nameparser.fieldnameparser.wsdl.SoapFieldNameParserResult
     * @throws AccessDeniedWebServiceException
     * @throws org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException
     * @throws InvalidInputWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parse", targetNamespace = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.nameparser.fieldnameparser.wsdl.Parse")
    @ResponseWrapper(localName = "parseResponse", targetNamespace = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.nameparser.fieldnameparser.wsdl.ParseResponse")
    @Action(input = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/SoapFieldNameParser/parseRequest", output = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/SoapFieldNameParser/parseResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/SoapFieldNameParser/parse/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/SoapFieldNameParser/parse/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/SoapFieldNameParser/parse/Fault/InternalServerErrorWebServiceException")
    })
    public SoapFieldNameParserResult parse(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "nameField", targetNamespace = "")
        SoapNameField nameField)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "price", targetNamespace = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.nameparser.fieldnameparser.wsdl.Price")
    @ResponseWrapper(localName = "priceResponse", targetNamespace = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.nameparser.fieldnameparser.wsdl.PriceResponse")
    @Action(input = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/SoapFieldNameParser/priceRequest", output = "http://fieldnameparser.nameparser.services.v4_0.soap.server.nameapi.org/SoapFieldNameParser/priceResponse")
    public int price();

}
