
package org.nameapi.client.services.validator.famouspersondetector.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapFamousPersonDetectorService", targetNamespace = "http://famouspersondetector.validator.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/validator/famouspersondetector?wsdl")
public class SoapFamousPersonDetectorService
    extends Service
{

    private final static URL SOAPFAMOUSPERSONDETECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPFAMOUSPERSONDETECTORSERVICE_EXCEPTION;
    private final static QName SOAPFAMOUSPERSONDETECTORSERVICE_QNAME = new QName("http://famouspersondetector.validator.services.v4_0.soap.server.nameapi.org/", "SoapFamousPersonDetectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/validator/famouspersondetector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPFAMOUSPERSONDETECTORSERVICE_WSDL_LOCATION = url;
        SOAPFAMOUSPERSONDETECTORSERVICE_EXCEPTION = e;
    }

    public SoapFamousPersonDetectorService() {
        super(__getWsdlLocation(), SOAPFAMOUSPERSONDETECTORSERVICE_QNAME);
    }

    public SoapFamousPersonDetectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPFAMOUSPERSONDETECTORSERVICE_QNAME, features);
    }

    public SoapFamousPersonDetectorService(URL wsdlLocation) {
        super(wsdlLocation, SOAPFAMOUSPERSONDETECTORSERVICE_QNAME);
    }

    public SoapFamousPersonDetectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPFAMOUSPERSONDETECTORSERVICE_QNAME, features);
    }

    public SoapFamousPersonDetectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapFamousPersonDetectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapFamousPersonDetector
     */
    @WebEndpoint(name = "SoapFamousPersonDetectorPort")
    public SoapFamousPersonDetector getSoapFamousPersonDetectorPort() {
        return super.getPort(new QName("http://famouspersondetector.validator.services.v4_0.soap.server.nameapi.org/", "SoapFamousPersonDetectorPort"), SoapFamousPersonDetector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapFamousPersonDetector
     */
    @WebEndpoint(name = "SoapFamousPersonDetectorPort")
    public SoapFamousPersonDetector getSoapFamousPersonDetectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://famouspersondetector.validator.services.v4_0.soap.server.nameapi.org/", "SoapFamousPersonDetectorPort"), SoapFamousPersonDetector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPFAMOUSPERSONDETECTORSERVICE_EXCEPTION!= null) {
            throw SOAPFAMOUSPERSONDETECTORSERVICE_EXCEPTION;
        }
        return SOAPFAMOUSPERSONDETECTORSERVICE_WSDL_LOCATION;
    }

}
