
package org.nameapi.client.services.nameparser.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapNameParserService", targetNamespace = "http://nameparser.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/nameparser?wsdl")
public class SoapNameParserService
    extends Service
{

    private final static URL SOAPNAMEPARSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPNAMEPARSERSERVICE_EXCEPTION;
    private final static QName SOAPNAMEPARSERSERVICE_QNAME = new QName("http://nameparser.services.v4_0.soap.server.nameapi.org/", "SoapNameParserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/nameparser?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPNAMEPARSERSERVICE_WSDL_LOCATION = url;
        SOAPNAMEPARSERSERVICE_EXCEPTION = e;
    }

    public SoapNameParserService() {
        super(__getWsdlLocation(), SOAPNAMEPARSERSERVICE_QNAME);
    }

    public SoapNameParserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPNAMEPARSERSERVICE_QNAME, features);
    }

    public SoapNameParserService(URL wsdlLocation) {
        super(wsdlLocation, SOAPNAMEPARSERSERVICE_QNAME);
    }

    public SoapNameParserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPNAMEPARSERSERVICE_QNAME, features);
    }

    public SoapNameParserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapNameParserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapNameParser
     */
    @WebEndpoint(name = "SoapNameParserPort")
    public SoapNameParser getSoapNameParserPort() {
        return super.getPort(new QName("http://nameparser.services.v4_0.soap.server.nameapi.org/", "SoapNameParserPort"), SoapNameParser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapNameParser
     */
    @WebEndpoint(name = "SoapNameParserPort")
    public SoapNameParser getSoapNameParserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nameparser.services.v4_0.soap.server.nameapi.org/", "SoapNameParserPort"), SoapNameParser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPNAMEPARSERSERVICE_EXCEPTION!= null) {
            throw SOAPNAMEPARSERSERVICE_EXCEPTION;
        }
        return SOAPNAMEPARSERSERVICE_WSDL_LOCATION;
    }

}
