
package org.nameapi.client.services.nameparser.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapNameParser", targetNamespace = "http://nameparser.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapNameParser {


    /**
     * 
     * @param nameString
     * @param context
     * @param rules
     * @return
     *     returns org.nameapi.client.services.nameparser.wsdl.SoapParserResult
     * @throws org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException
     * @throws AccessDeniedWebServiceException
     * @throws InvalidInputWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parse", targetNamespace = "http://nameparser.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.nameparser.wsdl.Parse")
    @ResponseWrapper(localName = "parseResponse", targetNamespace = "http://nameparser.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.nameparser.wsdl.ParseResponse")
    @Action(input = "http://nameparser.services.v4_0.soap.server.nameapi.org/SoapNameParser/parseRequest", output = "http://nameparser.services.v4_0.soap.server.nameapi.org/SoapNameParser/parseResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://nameparser.services.v4_0.soap.server.nameapi.org/SoapNameParser/parse/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://nameparser.services.v4_0.soap.server.nameapi.org/SoapNameParser/parse/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://nameparser.services.v4_0.soap.server.nameapi.org/SoapNameParser/parse/Fault/InternalServerErrorWebServiceException")
    })
    public SoapParserResult parse(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "nameString", targetNamespace = "")
        String nameString,
        @WebParam(name = "rules", targetNamespace = "")
        List<SoapNameParserRule> rules)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "price", targetNamespace = "http://nameparser.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.nameparser.wsdl.Price")
    @ResponseWrapper(localName = "priceResponse", targetNamespace = "http://nameparser.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.nameparser.wsdl.PriceResponse")
    @Action(input = "http://nameparser.services.v4_0.soap.server.nameapi.org/SoapNameParser/priceRequest", output = "http://nameparser.services.v4_0.soap.server.nameapi.org/SoapNameParser/priceResponse")
    public int price();

}
