
package org.nameapi.client.services.system.pinger.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapPinger", targetNamespace = "http://pinger.system.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapPinger {


    /**
     * 
     * @param context
     * @return
     *     returns org.nameapi.client.services.system.pinger.wsdl.SoapPingerResult
     * @throws AccessDeniedWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws InternalServerErrorWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://pinger.system.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.system.pinger.wsdl.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://pinger.system.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.system.pinger.wsdl.PingResponse")
    @Action(input = "http://pinger.system.services.v4_0.soap.server.nameapi.org/SoapPinger/pingRequest", output = "http://pinger.system.services.v4_0.soap.server.nameapi.org/SoapPinger/pingResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://pinger.system.services.v4_0.soap.server.nameapi.org/SoapPinger/ping/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://pinger.system.services.v4_0.soap.server.nameapi.org/SoapPinger/ping/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://pinger.system.services.v4_0.soap.server.nameapi.org/SoapPinger/ping/Fault/InternalServerErrorWebServiceException")
    })
    public SoapPingerResult ping(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
