
package org.nameapi.client.services.system.pinger.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapPingerService", targetNamespace = "http://pinger.system.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/system/pinger?wsdl")
public class SoapPingerService
    extends Service
{

    private final static URL SOAPPINGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPPINGERSERVICE_EXCEPTION;
    private final static QName SOAPPINGERSERVICE_QNAME = new QName("http://pinger.system.services.v4_0.soap.server.nameapi.org/", "SoapPingerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/system/pinger?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPPINGERSERVICE_WSDL_LOCATION = url;
        SOAPPINGERSERVICE_EXCEPTION = e;
    }

    public SoapPingerService() {
        super(__getWsdlLocation(), SOAPPINGERSERVICE_QNAME);
    }

    public SoapPingerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPPINGERSERVICE_QNAME, features);
    }

    public SoapPingerService(URL wsdlLocation) {
        super(wsdlLocation, SOAPPINGERSERVICE_QNAME);
    }

    public SoapPingerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPPINGERSERVICE_QNAME, features);
    }

    public SoapPingerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapPingerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapPinger
     */
    @WebEndpoint(name = "SoapPingerPort")
    public SoapPinger getSoapPingerPort() {
        return super.getPort(new QName("http://pinger.system.services.v4_0.soap.server.nameapi.org/", "SoapPingerPort"), SoapPinger.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapPinger
     */
    @WebEndpoint(name = "SoapPingerPort")
    public SoapPinger getSoapPingerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pinger.system.services.v4_0.soap.server.nameapi.org/", "SoapPingerPort"), SoapPinger.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPPINGERSERVICE_EXCEPTION!= null) {
            throw SOAPPINGERSERVICE_EXCEPTION;
        }
        return SOAPPINGERSERVICE_WSDL_LOCATION;
    }

}
