
package org.nameapi.client.services.genderizer.persongenderizer.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapPersonGenderizerService", targetNamespace = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/genderizer/persongenderizer?wsdl")
public class SoapPersonGenderizerService
    extends Service
{

    private final static URL SOAPPERSONGENDERIZERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPPERSONGENDERIZERSERVICE_EXCEPTION;
    private final static QName SOAPPERSONGENDERIZERSERVICE_QNAME = new QName("http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/", "SoapPersonGenderizerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/genderizer/persongenderizer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPPERSONGENDERIZERSERVICE_WSDL_LOCATION = url;
        SOAPPERSONGENDERIZERSERVICE_EXCEPTION = e;
    }

    public SoapPersonGenderizerService() {
        super(__getWsdlLocation(), SOAPPERSONGENDERIZERSERVICE_QNAME);
    }

    public SoapPersonGenderizerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPPERSONGENDERIZERSERVICE_QNAME, features);
    }

    public SoapPersonGenderizerService(URL wsdlLocation) {
        super(wsdlLocation, SOAPPERSONGENDERIZERSERVICE_QNAME);
    }

    public SoapPersonGenderizerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPPERSONGENDERIZERSERVICE_QNAME, features);
    }

    public SoapPersonGenderizerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapPersonGenderizerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapPersonGenderizer
     */
    @WebEndpoint(name = "SoapPersonGenderizerPort")
    public SoapPersonGenderizer getSoapPersonGenderizerPort() {
        return super.getPort(new QName("http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/", "SoapPersonGenderizerPort"), SoapPersonGenderizer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapPersonGenderizer
     */
    @WebEndpoint(name = "SoapPersonGenderizerPort")
    public SoapPersonGenderizer getSoapPersonGenderizerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/", "SoapPersonGenderizerPort"), SoapPersonGenderizer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPPERSONGENDERIZERSERVICE_EXCEPTION!= null) {
            throw SOAPPERSONGENDERIZERSERVICE_EXCEPTION;
        }
        return SOAPPERSONGENDERIZERSERVICE_WSDL_LOCATION;
    }

}
