
package org.nameapi.client.services.genderizer.persongenderizer.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;
import org.nameapi.client.commonwsdl.person.SoapSimpleNaturalPerson;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapPersonGenderizer", targetNamespace = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapPersonGenderizer {


    /**
     * 
     * @param person
     * @param context
     * @return
     *     returns org.nameapi.client.services.genderizer.persongenderizer.wsdl.SoapPersonGenderizerResult
     * @throws InvalidInputWebServiceException
     * @throws AccessDeniedWebServiceException
     * @throws InternalServerErrorWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assess", targetNamespace = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.genderizer.persongenderizer.wsdl.Assess")
    @ResponseWrapper(localName = "assessResponse", targetNamespace = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.genderizer.persongenderizer.wsdl.AssessResponse")
    @Action(input = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/SoapPersonGenderizer/assessRequest", output = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/SoapPersonGenderizer/assessResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/SoapPersonGenderizer/assess/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/SoapPersonGenderizer/assess/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://persongenderizer.genderizer.services.v4_0.soap.server.nameapi.org/SoapPersonGenderizer/assess/Fault/InternalServerErrorWebServiceException")
    })
    public SoapPersonGenderizerResult assess(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "person", targetNamespace = "")
        SoapSimpleNaturalPerson person)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
