
package org.nameapi.client.services.email.emailnameparser2.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapEmailNameParser2Service", targetNamespace = "http://emailnameparser2.email.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.1/email/emailnameparser2?wsdl")
public class SoapEmailNameParser2Service
    extends Service
{

    private final static URL SOAPEMAILNAMEPARSER2SERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPEMAILNAMEPARSER2SERVICE_EXCEPTION;
    private final static QName SOAPEMAILNAMEPARSER2SERVICE_QNAME = new QName("http://emailnameparser2.email.services.v4_0.soap.server.nameapi.org/", "SoapEmailNameParser2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.1/email/emailnameparser2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPEMAILNAMEPARSER2SERVICE_WSDL_LOCATION = url;
        SOAPEMAILNAMEPARSER2SERVICE_EXCEPTION = e;
    }

    public SoapEmailNameParser2Service() {
        super(__getWsdlLocation(), SOAPEMAILNAMEPARSER2SERVICE_QNAME);
    }

    public SoapEmailNameParser2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPEMAILNAMEPARSER2SERVICE_QNAME, features);
    }

    public SoapEmailNameParser2Service(URL wsdlLocation) {
        super(wsdlLocation, SOAPEMAILNAMEPARSER2SERVICE_QNAME);
    }

    public SoapEmailNameParser2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPEMAILNAMEPARSER2SERVICE_QNAME, features);
    }

    public SoapEmailNameParser2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapEmailNameParser2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapEmailNameParser2
     */
    @WebEndpoint(name = "SoapEmailNameParser2Port")
    public SoapEmailNameParser2 getSoapEmailNameParser2Port() {
        return super.getPort(new QName("http://emailnameparser2.email.services.v4_0.soap.server.nameapi.org/", "SoapEmailNameParser2Port"), SoapEmailNameParser2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapEmailNameParser2
     */
    @WebEndpoint(name = "SoapEmailNameParser2Port")
    public SoapEmailNameParser2 getSoapEmailNameParser2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://emailnameparser2.email.services.v4_0.soap.server.nameapi.org/", "SoapEmailNameParser2Port"), SoapEmailNameParser2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPEMAILNAMEPARSER2SERVICE_EXCEPTION!= null) {
            throw SOAPEMAILNAMEPARSER2SERVICE_EXCEPTION;
        }
        return SOAPEMAILNAMEPARSER2SERVICE_WSDL_LOCATION;
    }

}
