
package org.nameapi.client.services.formatter.personnameformatter.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapPersonNameFormatterService", targetNamespace = "http://personnameformatter.formatter.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/formatter/personnameformatter?wsdl")
public class SoapPersonNameFormatterService
    extends Service
{

    private final static URL SOAPPERSONNAMEFORMATTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPPERSONNAMEFORMATTERSERVICE_EXCEPTION;
    private final static QName SOAPPERSONNAMEFORMATTERSERVICE_QNAME = new QName("http://personnameformatter.formatter.services.v4_0.soap.server.nameapi.org/", "SoapPersonNameFormatterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/formatter/personnameformatter?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPPERSONNAMEFORMATTERSERVICE_WSDL_LOCATION = url;
        SOAPPERSONNAMEFORMATTERSERVICE_EXCEPTION = e;
    }

    public SoapPersonNameFormatterService() {
        super(__getWsdlLocation(), SOAPPERSONNAMEFORMATTERSERVICE_QNAME);
    }

    public SoapPersonNameFormatterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPPERSONNAMEFORMATTERSERVICE_QNAME, features);
    }

    public SoapPersonNameFormatterService(URL wsdlLocation) {
        super(wsdlLocation, SOAPPERSONNAMEFORMATTERSERVICE_QNAME);
    }

    public SoapPersonNameFormatterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPPERSONNAMEFORMATTERSERVICE_QNAME, features);
    }

    public SoapPersonNameFormatterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapPersonNameFormatterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapPersonNameFormatter
     */
    @WebEndpoint(name = "SoapPersonNameFormatterPort")
    public SoapPersonNameFormatter getSoapPersonNameFormatterPort() {
        return super.getPort(new QName("http://personnameformatter.formatter.services.v4_0.soap.server.nameapi.org/", "SoapPersonNameFormatterPort"), SoapPersonNameFormatter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapPersonNameFormatter
     */
    @WebEndpoint(name = "SoapPersonNameFormatterPort")
    public SoapPersonNameFormatter getSoapPersonNameFormatterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://personnameformatter.formatter.services.v4_0.soap.server.nameapi.org/", "SoapPersonNameFormatterPort"), SoapPersonNameFormatter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPPERSONNAMEFORMATTERSERVICE_EXCEPTION!= null) {
            throw SOAPPERSONNAMEFORMATTERSERVICE_EXCEPTION;
        }
        return SOAPPERSONNAMEFORMATTERSERVICE_WSDL_LOCATION;
    }

}
