
package org.nameapi.client.services.email.emaildomaintypeclassifier.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapEmailDomainTypeClassifierService", targetNamespace = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/email/emaildomaintypeclassifier?wsdl")
public class SoapEmailDomainTypeClassifierService
    extends Service
{

    private final static URL SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_EXCEPTION;
    private final static QName SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_QNAME = new QName("http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/", "SoapEmailDomainTypeClassifierService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/email/emaildomaintypeclassifier?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_WSDL_LOCATION = url;
        SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_EXCEPTION = e;
    }

    public SoapEmailDomainTypeClassifierService() {
        super(__getWsdlLocation(), SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_QNAME);
    }

    public SoapEmailDomainTypeClassifierService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_QNAME, features);
    }

    public SoapEmailDomainTypeClassifierService(URL wsdlLocation) {
        super(wsdlLocation, SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_QNAME);
    }

    public SoapEmailDomainTypeClassifierService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_QNAME, features);
    }

    public SoapEmailDomainTypeClassifierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapEmailDomainTypeClassifierService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapEmailDomainTypeClassifier
     */
    @WebEndpoint(name = "SoapEmailDomainTypeClassifierPort")
    public SoapEmailDomainTypeClassifier getSoapEmailDomainTypeClassifierPort() {
        return super.getPort(new QName("http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/", "SoapEmailDomainTypeClassifierPort"), SoapEmailDomainTypeClassifier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapEmailDomainTypeClassifier
     */
    @WebEndpoint(name = "SoapEmailDomainTypeClassifierPort")
    public SoapEmailDomainTypeClassifier getSoapEmailDomainTypeClassifierPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/", "SoapEmailDomainTypeClassifierPort"), SoapEmailDomainTypeClassifier.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_EXCEPTION!= null) {
            throw SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_EXCEPTION;
        }
        return SOAPEMAILDOMAINTYPECLASSIFIERSERVICE_WSDL_LOCATION;
    }

}
