
package org.nameapi.client.services.email.emaildomaintypeclassifier.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapEmailDomainTypeClassifier", targetNamespace = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapEmailDomainTypeClassifier {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "price", targetNamespace = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.email.emaildomaintypeclassifier.wsdl.Price")
    @ResponseWrapper(localName = "priceResponse", targetNamespace = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.email.emaildomaintypeclassifier.wsdl.PriceResponse")
    @Action(input = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/SoapEmailDomainTypeClassifier/priceRequest", output = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/SoapEmailDomainTypeClassifier/priceResponse")
    public int price();

    /**
     * 
     * @param context
     * @param emailAddress
     * @return
     *     returns org.nameapi.client.services.email.emaildomaintypeclassifier.wsdl.EmailDomainType
     * @throws org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws AccessDeniedWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "classify", targetNamespace = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.email.emaildomaintypeclassifier.wsdl.Classify")
    @ResponseWrapper(localName = "classifyResponse", targetNamespace = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.email.emaildomaintypeclassifier.wsdl.ClassifyResponse")
    @Action(input = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/SoapEmailDomainTypeClassifier/classifyRequest", output = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/SoapEmailDomainTypeClassifier/classifyResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/SoapEmailDomainTypeClassifier/classify/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/SoapEmailDomainTypeClassifier/classify/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://emaildomaintypeclassifier.email.services.v4_0.soap.server.nameapi.org/SoapEmailDomainTypeClassifier/classify/Fault/InternalServerErrorWebServiceException")
    })
    public EmailDomainType classify(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "emailAddress", targetNamespace = "")
        String emailAddress)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
