
package org.nameapi.client.services.parser.personnameparser.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapPersonNameParserService", targetNamespace = "http://personnameparser.parser.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/parser/personnameparser?wsdl")
public class SoapPersonNameParserService
    extends Service
{

    private final static URL SOAPPERSONNAMEPARSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPPERSONNAMEPARSERSERVICE_EXCEPTION;
    private final static QName SOAPPERSONNAMEPARSERSERVICE_QNAME = new QName("http://personnameparser.parser.services.v4_0.soap.server.nameapi.org/", "SoapPersonNameParserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/parser/personnameparser?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPPERSONNAMEPARSERSERVICE_WSDL_LOCATION = url;
        SOAPPERSONNAMEPARSERSERVICE_EXCEPTION = e;
    }

    public SoapPersonNameParserService() {
        super(__getWsdlLocation(), SOAPPERSONNAMEPARSERSERVICE_QNAME);
    }

    public SoapPersonNameParserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPPERSONNAMEPARSERSERVICE_QNAME, features);
    }

    public SoapPersonNameParserService(URL wsdlLocation) {
        super(wsdlLocation, SOAPPERSONNAMEPARSERSERVICE_QNAME);
    }

    public SoapPersonNameParserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPPERSONNAMEPARSERSERVICE_QNAME, features);
    }

    public SoapPersonNameParserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapPersonNameParserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapPersonNameParser
     */
    @WebEndpoint(name = "SoapPersonNameParserPort")
    public SoapPersonNameParser getSoapPersonNameParserPort() {
        return super.getPort(new QName("http://personnameparser.parser.services.v4_0.soap.server.nameapi.org/", "SoapPersonNameParserPort"), SoapPersonNameParser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapPersonNameParser
     */
    @WebEndpoint(name = "SoapPersonNameParserPort")
    public SoapPersonNameParser getSoapPersonNameParserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://personnameparser.parser.services.v4_0.soap.server.nameapi.org/", "SoapPersonNameParserPort"), SoapPersonNameParser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPPERSONNAMEPARSERSERVICE_EXCEPTION!= null) {
            throw SOAPPERSONNAMEPARSERSERVICE_EXCEPTION;
        }
        return SOAPPERSONNAMEPARSERSERVICE_WSDL_LOCATION;
    }

}
