
package org.nameapi.client.services.validator.gender.genericgendervalidator.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapGenericGenderValidatorService", targetNamespace = "http://genericgendervalidator.gender.validator.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/validator/gender/genericgendervalidator?wsdl")
public class SoapGenericGenderValidatorService
    extends Service
{

    private final static URL SOAPGENERICGENDERVALIDATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPGENERICGENDERVALIDATORSERVICE_EXCEPTION;
    private final static QName SOAPGENERICGENDERVALIDATORSERVICE_QNAME = new QName("http://genericgendervalidator.gender.validator.services.v4_0.soap.server.nameapi.org/", "SoapGenericGenderValidatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/validator/gender/genericgendervalidator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPGENERICGENDERVALIDATORSERVICE_WSDL_LOCATION = url;
        SOAPGENERICGENDERVALIDATORSERVICE_EXCEPTION = e;
    }

    public SoapGenericGenderValidatorService() {
        super(__getWsdlLocation(), SOAPGENERICGENDERVALIDATORSERVICE_QNAME);
    }

    public SoapGenericGenderValidatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPGENERICGENDERVALIDATORSERVICE_QNAME, features);
    }

    public SoapGenericGenderValidatorService(URL wsdlLocation) {
        super(wsdlLocation, SOAPGENERICGENDERVALIDATORSERVICE_QNAME);
    }

    public SoapGenericGenderValidatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPGENERICGENDERVALIDATORSERVICE_QNAME, features);
    }

    public SoapGenericGenderValidatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapGenericGenderValidatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapGenericGenderValidator
     */
    @WebEndpoint(name = "SoapGenericGenderValidatorPort")
    public SoapGenericGenderValidator getSoapGenericGenderValidatorPort() {
        return super.getPort(new QName("http://genericgendervalidator.gender.validator.services.v4_0.soap.server.nameapi.org/", "SoapGenericGenderValidatorPort"), SoapGenericGenderValidator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapGenericGenderValidator
     */
    @WebEndpoint(name = "SoapGenericGenderValidatorPort")
    public SoapGenericGenderValidator getSoapGenericGenderValidatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://genericgendervalidator.gender.validator.services.v4_0.soap.server.nameapi.org/", "SoapGenericGenderValidatorPort"), SoapGenericGenderValidator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPGENERICGENDERVALIDATORSERVICE_EXCEPTION!= null) {
            throw SOAPGENERICGENDERVALIDATORSERVICE_EXCEPTION;
        }
        return SOAPGENERICGENDERVALIDATORSERVICE_WSDL_LOCATION;
    }

}
