
package org.nameapi.client.commonwsdl.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InternalServerErrorWebServiceException", targetNamespace = "http://ping.system.services.v4_0.soap.server.nameapi.org/")
public class InternalServerErrorWebServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultBean faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InternalServerErrorWebServiceException(String message, FaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InternalServerErrorWebServiceException(String message, FaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.nameapi.client.commonwsdl.exception.FaultBean
     */
    public FaultBean getFaultInfo() {
        return faultInfo;
    }

}
