
package org.nameapi.client.services.validator.randomtyping.givennamerandomtypingdetector.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapGivenNameRandomTypingDetectorService", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/validator/randomtypingdetector/givennamefield?wsdl")
public class SoapGivenNameRandomTypingDetectorService
    extends Service
{

    private final static URL SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_EXCEPTION;
    private final static QName SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_QNAME = new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapGivenNameRandomTypingDetectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/validator/randomtypingdetector/givennamefield?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION = url;
        SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_EXCEPTION = e;
    }

    public SoapGivenNameRandomTypingDetectorService() {
        super(__getWsdlLocation(), SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_QNAME);
    }

    public SoapGivenNameRandomTypingDetectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_QNAME, features);
    }

    public SoapGivenNameRandomTypingDetectorService(URL wsdlLocation) {
        super(wsdlLocation, SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_QNAME);
    }

    public SoapGivenNameRandomTypingDetectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_QNAME, features);
    }

    public SoapGivenNameRandomTypingDetectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapGivenNameRandomTypingDetectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapGivenNameRandomTypingDetector
     */
    @WebEndpoint(name = "SoapGivenNameRandomTypingDetectorPort")
    public SoapGivenNameRandomTypingDetector getSoapGivenNameRandomTypingDetectorPort() {
        return super.getPort(new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapGivenNameRandomTypingDetectorPort"), SoapGivenNameRandomTypingDetector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapGivenNameRandomTypingDetector
     */
    @WebEndpoint(name = "SoapGivenNameRandomTypingDetectorPort")
    public SoapGivenNameRandomTypingDetector getSoapGivenNameRandomTypingDetectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapGivenNameRandomTypingDetectorPort"), SoapGivenNameRandomTypingDetector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_EXCEPTION!= null) {
            throw SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_EXCEPTION;
        }
        return SOAPGIVENNAMERANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION;
    }

}
