
package org.nameapi.client.services.validator.randomtyping.textfieldrandomtypingdetector.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapTextFieldRandomTypingDetector", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapTextFieldRandomTypingDetector {


    /**
     * 
     * @param context
     * @param textField
     * @return
     *     returns java.lang.Integer
     * @throws AccessDeniedWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "check", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.randomtyping.textfieldrandomtypingdetector.wsdl.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.randomtyping.textfieldrandomtypingdetector.wsdl.CheckResponse")
    @Action(input = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapTextFieldRandomTypingDetector/checkRequest", output = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapTextFieldRandomTypingDetector/checkResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapTextFieldRandomTypingDetector/check/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapTextFieldRandomTypingDetector/check/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapTextFieldRandomTypingDetector/check/Fault/InternalServerErrorWebServiceException")
    })
    public Integer check(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "textField", targetNamespace = "")
        String textField)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "price", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.randomtyping.textfieldrandomtypingdetector.wsdl.Price")
    @ResponseWrapper(localName = "priceResponse", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.randomtyping.textfieldrandomtypingdetector.wsdl.PriceResponse")
    @Action(input = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapTextFieldRandomTypingDetector/priceRequest", output = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapTextFieldRandomTypingDetector/priceResponse")
    public int price();

}
