
package org.nameapi.client.services.validator.randomtyping.textfieldrandomtypingdetector.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapTextFieldRandomTypingDetectorService", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/validator/randomtypingdetector/textfield?wsdl")
public class SoapTextFieldRandomTypingDetectorService
    extends Service
{

    private final static URL SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_EXCEPTION;
    private final static QName SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_QNAME = new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapTextFieldRandomTypingDetectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/validator/randomtypingdetector/textfield?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION = url;
        SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_EXCEPTION = e;
    }

    public SoapTextFieldRandomTypingDetectorService() {
        super(__getWsdlLocation(), SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_QNAME);
    }

    public SoapTextFieldRandomTypingDetectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_QNAME, features);
    }

    public SoapTextFieldRandomTypingDetectorService(URL wsdlLocation) {
        super(wsdlLocation, SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_QNAME);
    }

    public SoapTextFieldRandomTypingDetectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_QNAME, features);
    }

    public SoapTextFieldRandomTypingDetectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapTextFieldRandomTypingDetectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapTextFieldRandomTypingDetector
     */
    @WebEndpoint(name = "SoapTextFieldRandomTypingDetectorPort")
    public SoapTextFieldRandomTypingDetector getSoapTextFieldRandomTypingDetectorPort() {
        return super.getPort(new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapTextFieldRandomTypingDetectorPort"), SoapTextFieldRandomTypingDetector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapTextFieldRandomTypingDetector
     */
    @WebEndpoint(name = "SoapTextFieldRandomTypingDetectorPort")
    public SoapTextFieldRandomTypingDetector getSoapTextFieldRandomTypingDetectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapTextFieldRandomTypingDetectorPort"), SoapTextFieldRandomTypingDetector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_EXCEPTION!= null) {
            throw SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_EXCEPTION;
        }
        return SOAPTEXTFIELDRANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION;
    }

}
