
package org.nameapi.client.services.matcher.personmatcher.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapPersonMatcherService", targetNamespace = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/matcher/personmatcher?wsdl")
public class SoapPersonMatcherService
    extends Service
{

    private final static URL SOAPPERSONMATCHERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPPERSONMATCHERSERVICE_EXCEPTION;
    private final static QName SOAPPERSONMATCHERSERVICE_QNAME = new QName("http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/", "SoapPersonMatcherService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/matcher/personmatcher?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPPERSONMATCHERSERVICE_WSDL_LOCATION = url;
        SOAPPERSONMATCHERSERVICE_EXCEPTION = e;
    }

    public SoapPersonMatcherService() {
        super(__getWsdlLocation(), SOAPPERSONMATCHERSERVICE_QNAME);
    }

    public SoapPersonMatcherService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPPERSONMATCHERSERVICE_QNAME, features);
    }

    public SoapPersonMatcherService(URL wsdlLocation) {
        super(wsdlLocation, SOAPPERSONMATCHERSERVICE_QNAME);
    }

    public SoapPersonMatcherService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPPERSONMATCHERSERVICE_QNAME, features);
    }

    public SoapPersonMatcherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapPersonMatcherService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapPersonMatcher
     */
    @WebEndpoint(name = "SoapPersonMatcherPort")
    public SoapPersonMatcher getSoapPersonMatcherPort() {
        return super.getPort(new QName("http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/", "SoapPersonMatcherPort"), SoapPersonMatcher.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapPersonMatcher
     */
    @WebEndpoint(name = "SoapPersonMatcherPort")
    public SoapPersonMatcher getSoapPersonMatcherPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/", "SoapPersonMatcherPort"), SoapPersonMatcher.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPPERSONMATCHERSERVICE_EXCEPTION!= null) {
            throw SOAPPERSONMATCHERSERVICE_EXCEPTION;
        }
        return SOAPPERSONMATCHERSERVICE_WSDL_LOCATION;
    }

}
