
package org.nameapi.client.services.matcher.personmatcher.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;
import org.nameapi.client.commonwsdl.person.SoapSimpleNaturalPerson;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapPersonMatcher", targetNamespace = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapPersonMatcher {


    /**
     * 
     * @param person1
     * @param person2
     * @param context
     * @return
     *     returns org.nameapi.client.services.matcher.personmatcher.wsdl.SoapPersonMatcherResult
     * @throws AccessDeniedWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws InternalServerErrorWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "match", targetNamespace = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.matcher.personmatcher.wsdl.Match")
    @ResponseWrapper(localName = "matchResponse", targetNamespace = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.matcher.personmatcher.wsdl.MatchResponse")
    @Action(input = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/SoapPersonMatcher/matchRequest", output = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/SoapPersonMatcher/matchResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/SoapPersonMatcher/match/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/SoapPersonMatcher/match/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://personmatcher.matcher.services.v4_0.soap.server.nameapi.org/SoapPersonMatcher/match/Fault/InternalServerErrorWebServiceException")
    })
    public SoapPersonMatcherResult match(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "person1", targetNamespace = "")
        SoapSimpleNaturalPerson person1,
        @WebParam(name = "person2", targetNamespace = "")
        SoapSimpleNaturalPerson person2)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
