
package org.nameapi.client.services.validator.randomtyping.surnamerandomtypingdetector.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapSurnameRandomTypingDetectorService", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/validator/randomtypingdetector/surnamefield?wsdl")
public class SoapSurnameRandomTypingDetectorService
    extends Service
{

    private final static URL SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_EXCEPTION;
    private final static QName SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_QNAME = new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapSurnameRandomTypingDetectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/validator/randomtypingdetector/surnamefield?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION = url;
        SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_EXCEPTION = e;
    }

    public SoapSurnameRandomTypingDetectorService() {
        super(__getWsdlLocation(), SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_QNAME);
    }

    public SoapSurnameRandomTypingDetectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_QNAME, features);
    }

    public SoapSurnameRandomTypingDetectorService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_QNAME);
    }

    public SoapSurnameRandomTypingDetectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_QNAME, features);
    }

    public SoapSurnameRandomTypingDetectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapSurnameRandomTypingDetectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapSurnameRandomTypingDetector
     */
    @WebEndpoint(name = "SoapSurnameRandomTypingDetectorPort")
    public SoapSurnameRandomTypingDetector getSoapSurnameRandomTypingDetectorPort() {
        return super.getPort(new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapSurnameRandomTypingDetectorPort"), SoapSurnameRandomTypingDetector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapSurnameRandomTypingDetector
     */
    @WebEndpoint(name = "SoapSurnameRandomTypingDetectorPort")
    public SoapSurnameRandomTypingDetector getSoapSurnameRandomTypingDetectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapSurnameRandomTypingDetectorPort"), SoapSurnameRandomTypingDetector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_EXCEPTION!= null) {
            throw SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_EXCEPTION;
        }
        return SOAPSURNAMERANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION;
    }

}
