
package org.nameapi.client.services.validator.randomtyping.surnamerandomtypingdetector.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapSurnameRandomTypingDetector", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapSurnameRandomTypingDetector {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "price", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.randomtyping.surnamerandomtypingdetector.wsdl.Price")
    @ResponseWrapper(localName = "priceResponse", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.randomtyping.surnamerandomtypingdetector.wsdl.PriceResponse")
    @Action(input = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapSurnameRandomTypingDetector/priceRequest", output = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapSurnameRandomTypingDetector/priceResponse")
    public int price();

    /**
     * 
     * @param term
     * @param context
     * @return
     *     returns java.lang.Integer
     * @throws AccessDeniedWebServiceException
     * @throws org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException
     * @throws InvalidInputWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkField", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.randomtyping.surnamerandomtypingdetector.wsdl.CheckField")
    @ResponseWrapper(localName = "checkFieldResponse", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.validator.randomtyping.surnamerandomtypingdetector.wsdl.CheckFieldResponse")
    @Action(input = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapSurnameRandomTypingDetector/checkFieldRequest", output = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapSurnameRandomTypingDetector/checkFieldResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapSurnameRandomTypingDetector/checkField/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapSurnameRandomTypingDetector/checkField/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/SoapSurnameRandomTypingDetector/checkField/Fault/InternalServerErrorWebServiceException")
    })
    public Integer checkField(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "term", targetNamespace = "")
        String term)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
