
package org.nameapi.client.services.email.disposableemailaddressdetector.wsdl;

import org.nameapi.client.commonwsdl.context.SoapContext;
import org.nameapi.client.commonwsdl.exception.AccessDeniedWebServiceException;
import org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException;
import org.nameapi.client.commonwsdl.exception.InvalidInputWebServiceException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapDisposableEmailAddressDetector", targetNamespace = "http://disposableemailaddressdetector.email.services.v4_0.soap.server.nameapi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapDisposableEmailAddressDetector {


    /**
     * 
     * @param context
     * @param emailAddress
     * @return
     *     returns org.nameapi.client.services.email.disposableemailaddressdetector.wsdl.SoapDisposableEmailAddressDetectorResult
     * @throws InvalidInputWebServiceException
     * @throws org.nameapi.client.commonwsdl.exception.InternalServerErrorWebServiceException
     * @throws AccessDeniedWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isDisposable", targetNamespace = "http://disposableemailaddressdetector.email.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.email.disposableemailaddressdetector.wsdl.IsDisposable")
    @ResponseWrapper(localName = "isDisposableResponse", targetNamespace = "http://disposableemailaddressdetector.email.services.v4_0.soap.server.nameapi.org/", className = "org.nameapi.client.services.email.disposableemailaddressdetector.wsdl.IsDisposableResponse")
    @Action(input = "http://disposableemailaddressdetector.email.services.v4_0.soap.server.nameapi.org/SoapDisposableEmailAddressDetector/isDisposableRequest", output = "http://disposableemailaddressdetector.email.services.v4_0.soap.server.nameapi.org/SoapDisposableEmailAddressDetector/isDisposableResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://disposableemailaddressdetector.email.services.v4_0.soap.server.nameapi.org/SoapDisposableEmailAddressDetector/isDisposable/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://disposableemailaddressdetector.email.services.v4_0.soap.server.nameapi.org/SoapDisposableEmailAddressDetector/isDisposable/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://disposableemailaddressdetector.email.services.v4_0.soap.server.nameapi.org/SoapDisposableEmailAddressDetector/isDisposable/Fault/InternalServerErrorWebServiceException")
    })
    public SoapDisposableEmailAddressDetectorResult isDisposable(
        @WebParam(name = "context", targetNamespace = "")
        SoapContext context,
        @WebParam(name = "emailAddress", targetNamespace = "")
        String emailAddress)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
