
package org.nameapi.client.services.validator.randomtyping.personrandomtypingdetector.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapPersonRandomTypingDetectorService", targetNamespace = "http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", wsdlLocation = "http://api.nameapi.org:80/soap/v4.0/validator/randomtypingdetector/person?wsdl")
public class SoapPersonRandomTypingDetectorService
    extends Service
{

    private final static URL SOAPPERSONRANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPPERSONRANDOMTYPINGDETECTORSERVICE_EXCEPTION;
    private final static QName SOAPPERSONRANDOMTYPINGDETECTORSERVICE_QNAME = new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapPersonRandomTypingDetectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.nameapi.org:80/soap/v4.0/validator/randomtypingdetector/person?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPPERSONRANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION = url;
        SOAPPERSONRANDOMTYPINGDETECTORSERVICE_EXCEPTION = e;
    }

    public SoapPersonRandomTypingDetectorService() {
        super(__getWsdlLocation(), SOAPPERSONRANDOMTYPINGDETECTORSERVICE_QNAME);
    }

    public SoapPersonRandomTypingDetectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPPERSONRANDOMTYPINGDETECTORSERVICE_QNAME, features);
    }

    public SoapPersonRandomTypingDetectorService(URL wsdlLocation) {
        super(wsdlLocation, SOAPPERSONRANDOMTYPINGDETECTORSERVICE_QNAME);
    }

    public SoapPersonRandomTypingDetectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPPERSONRANDOMTYPINGDETECTORSERVICE_QNAME, features);
    }

    public SoapPersonRandomTypingDetectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapPersonRandomTypingDetectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapPersonRandomTypingDetector
     */
    @WebEndpoint(name = "SoapPersonRandomTypingDetectorPort")
    public SoapPersonRandomTypingDetector getSoapPersonRandomTypingDetectorPort() {
        return super.getPort(new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapPersonRandomTypingDetectorPort"), SoapPersonRandomTypingDetector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapPersonRandomTypingDetector
     */
    @WebEndpoint(name = "SoapPersonRandomTypingDetectorPort")
    public SoapPersonRandomTypingDetector getSoapPersonRandomTypingDetectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://randomtyping.validator.services.v4_0.soap.server.nameapi.org/", "SoapPersonRandomTypingDetectorPort"), SoapPersonRandomTypingDetector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPPERSONRANDOMTYPINGDETECTORSERVICE_EXCEPTION!= null) {
            throw SOAPPERSONRANDOMTYPINGDETECTORSERVICE_EXCEPTION;
        }
        return SOAPPERSONRANDOMTYPINGDETECTORSERVICE_WSDL_LOCATION;
    }

}
